### ISSUE TITLE
got error with build.sh on ubuntu 18.04

### ISSUE THREAD

**Issue by carlhung** [pmacro/Stride#2]
$ ./build.sh
Swift version 5.0.1 (swift-5.0.1-RELEASE) Target: x86_64-unknown-linux-gnu
Using Yoga in: /home/carlhung/Stride/./.build/checkouts/Yoga/Sources/Yoga/linux-gnu
Using Clipboard in: /home/carlhung/Stride/./.build/checkouts/CClipboard/Sources/CClipboard
'X11' /home/carlhung/Stride/.build/checkouts/X11: warning: system packages are deprecated; use system library targets instead
'GLib' glib.pc: warning: couldn't find pc file
'FreeType' libfreetype.pc: warning: couldn't find pc file
/home/carlhung/Stride/Sources/StrideLib/EditorComponent.swift:415:68: error: extra argument 'toLine' in call
        editorComponent.editorView.scroll(toLine: range.start.line + 1)
                                                  ~~~~~~~~~~~~~~~~~^~~
/home/carlhung/Stride/Sources/StrideLib/SwiftFormatter.swift:24:13: warning: 'launch()' is deprecated: renamed to 'run'
    process.launch()
            ^
/home/carlhung/Stride/Sources/StrideLib/SwiftFormatter.swift:24:13: note: use 'run' instead
    process.launch()
            ^~~~~~
            run

Installing assets into /home/carlhung/Stride/.build/x86_64-unknown-linux/debug

**Comment by pmacro** [comment]
Hi Carl,

I made some changes in Suit yesterday that seem to be missing from your Stride environment.  The fix will depend on whether or not your Suit is in edit mode:

- If it's not in edit mode, i.e. Packages/Suit doesn't exist, then: `swift package update` followed by `./build.sh` should fix it.

- If it is in edit mode, i.e. Packages/Suit does exist, then: `cd Packages/Suit`, `git pull`, followed by `./build.sh` back in the Stride root should fix it.

Thanks for raising these issues for all the problems you've encountered, but the way.  Very much appreciated!

Paul

**Comment by carlhung** [comment]
none of these work.

**Comment by carlhung** [comment]
i remove all the packages. it seems like working now.

**Comment by pmacro** [comment]
Great!
